server:
  port: 80
logging:
  config: classpath:logback.xml
#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://47.95.117.48:3306/wx?useUnicode: true&characterEncoding: utf8
#    username: root
#    password: '!QAZ2wsx'
#    max-idle: 10
#    max-wait: 10000
#    min-idle: 5
#    initial-size: 5
#    type: com.alibaba.druid.pool.DruidDataSource


#spring: 
  #mvc: 
    #view: 
      #suffix: .html
      
netty:
  server:
    port: 8011
      
      
spring: 
  mvc:
    favicon: 
      enabled: false
  redis: 
    database: 1
    host: 34.80.16.28
    port: 6379
    password: Shotacon.1qaz
    timeout: 3000
  thymeleaf: 
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false
    chain: 
      strategy: 
        content: 
          enabled: true
          paths: /**
  # MongoDB
  data: 
    mongodb: 
      #uri: mongodb://@47.95.117.48:27017/user
          

